''' VectorStore Protocol: chunk embeddings, one collection per tenant.

Mirrors `blob.py` deliberately -- same Protocol-plus-one-impl shape, same reason: the
local service is the learning target and the managed one (Qdrant Cloud, Pinecone) is
a later swap behind the same two methods.

Tenant isolation is the collection name, not a payload filter. A filter is one
forgotten `must` clause away from serving another client's chart notes; a wrong
collection name raises "collection not found" and fails closed. In a HIPAA-shaped
system that difference is the whole design.
'''

import uuid
from dataclasses import dataclass, field
from typing import Protocol

# Fixed namespace, never regenerate it: point ids must stay stable across processes
# and releases, or a re-embed writes a second copy of every chunk instead of
# overwriting the first.
POINT_NAMESPACE = uuid.UUID("6f2b0e4c-0a7d-5f3e-9c21-4b8e7a1d0c55")


@dataclass
class Point:
    id: str
    vector: list[float]
    payload: dict = field(default_factory=dict)


class VectorStore(Protocol):
    def upsert(self, collection: str, points: list[Point]) -> None: ...
    def drop(self, collection: str) -> None: ...


def tenant_collection(tenant_id: uuid.UUID) -> str:
    return f"chunks_{tenant_id}"


def point_id(document_id: uuid.UUID, page_no: int, idx: int) -> str:
    ''' Deterministic, so an upsert after a crashed embed job overwrites the chunk it
    already wrote. An autogenerated id would duplicate every chunk on every retry and
    skew retrieval toward whichever document failed the most. '''
    return str(uuid.uuid5(POINT_NAMESPACE, f"{document_id}:{page_no}:{idx}"))


class QdrantVectorStore:
    ''' Single-node qdrant from docker-compose. See NORMALIZATION.md §3.1 for what
    changes at enterprise scale (HA, per-tenant collection ceilings). '''

    def __init__(self, url: str, dim: int) -> None:
        self.url = url
        self.dim = dim
        self._client = None
        self._ensured: set[str] = set()

    @property
    def client(self):
        if self._client is None:
            from qdrant_client import QdrantClient

            self._client = QdrantClient(url=self.url)
        return self._client

    def _ensure(self, collection: str) -> None:
        ''' Create on first write. A tenant's collection cannot be provisioned at
        signup -- the tenant row predates this service existing. '''
        if collection in self._ensured:
            return
        from qdrant_client.models import Distance, VectorParams

        if not self.client.collection_exists(collection):
            self.client.create_collection(
                collection,
                vectors_config=VectorParams(size=self.dim, distance=Distance.COSINE),
            )
        # ponytail: cached per process, so an out-of-band collection delete is not
        # noticed until restart. Drop the cache if collections start being managed
        # anywhere but here.
        self._ensured.add(collection)

    def upsert(self, collection: str, points: list[Point]) -> None:
        if not points:
            return
        from qdrant_client.models import PointStruct

        self._ensure(collection)
        self.client.upsert(
            collection_name=collection,
            points=[
                PointStruct(id=p.id, vector=p.vector, payload=p.payload)
                for p in points
            ],
            wait=True,  # the status flip to EMBEDDED must not outrun the write
        )

    def drop(self, collection: str) -> None:
        ''' Tenant offboarding and test teardown. Postgres keeps `document_pages`, so
        a dropped collection is rebuildable -- that is the point of keeping OCR text. '''
        self._ensured.discard(collection)
        self.client.delete_collection(collection)
